quotes/app_quotes/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'app_quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('quotes/', views.main, name='quotes'),
    path('authors/', views.authors, name='authors'),
    path('add_author/', views.add_author, name='add_author'),
    path("tags/", views.tags, name='tags'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_quotes.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView,\
    PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView


app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="app_quotes/quotes.html"), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/app_quotes/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    id = models.AutoField(primary_key=True)
    fullname = models.CharField(unique=True, max_length=100)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=500, null=False)
    description = models.TextField(null=False)
    user = models.ForeignKey(User, to_field="id", on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.fullname}"


class Quote(models.Model):
    id = models.AutoField(primary_key=True)
    quote = models.TextField(unique=True, null=False)
    author = models.ForeignKey(Author, to_field="id", on_delete=models.CASCADE)
    tags = ArrayField(models.CharField(max_length=50), null=False, blank=True)

    def __str__(self):
        return f"{self.tags}"

quotes/app_quotes/forms.py
from django.forms import DateField, DateInput, HiddenInput, IntegerField, ModelForm, CharField, TextInput, Select, \
    ModelChoiceField, JSONField, Textarea
from .models import Author, Quote


class AuthorForm(ModelForm):
    id = IntegerField(widget=HiddenInput(), required=False)
    fullname = CharField(min_length=3, max_length=25, widget=TextInput(attrs={"class": "form-control"}))
    born_date = DateField(widget=DateInput(attrs={"type": "date", "class": "form-control"}))
    born_location = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(max_length=2700, widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    id = IntegerField(widget=HiddenInput(), required=False)
    quote = CharField(max_length=1500, required=True, widget=TextInput(attrs={"class": "form-control"}))
    author = ModelChoiceField(queryset=Author.objects.all(), required=True,
                              widget=Select(attrs={"class": "form-control"}))
    tags = JSONField(max_length=500, required=False, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

quotes/app_quotes/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .forms import AuthorForm, QuoteForm
from .models import Author, Quote

# Create your views here.


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'app_quotes/quotes.html', context={'quotes': quotes})


def authors(request):
    if request.GET.get("id", ''):
        authors = Author.objects.all().filter(id=request.GET.get("id", ''))
    else:
        authors = Author.objects.all()
    return render(request, 'app_quotes/authors.html', context={'authors': authors})


def tags(request):
    search_tag = request.GET.get("tag", '')
    if search_tag:
        quotes = Quote.objects.filter(tags__icontains=search_tag)
    else:
        quotes = Quote.objects.all()

    return render(request, 'app_quotes/tags.html', context={'quotes': quotes, 'tag': search_tag})


@login_required
def add_author(request):
    form_author = AuthorForm(instance=Author())
    if request.method == "POST":
        form_author = AuthorForm(request.POST, instance=Author())
        if form_author.is_valid():
            form_author.save()
            return redirect(to='app_quotes:authors')

    return render(request, 'app_quotes/add_author.html', context={'form_author': form_author})


@login_required
def add_quote(request):
    form_quote = QuoteForm(instance=Quote())
    if request.method == "POST":
        my_request = request.POST.dict()
        my_request["tags"] = my_request["tags"].replace(r", ", " ").replace(r",", " ").strip().split(" ")
        form_quote = QuoteForm(my_request, instance=Quote())
        if form_quote.is_valid():
            form_quote.save()
            return redirect(to='app_quotes:quotes')

    return render(request, 'app_quotes/add_quote.html', context={'form_quote': form_quote})

quotes/app_quotes/templates/app_quotes/add_author.html
{% extends "app_quotes/base.html" %}

{% block content %}

<form action="{% url 'app_quotes:add_author' %}" method="POST" enctype="multipart/form-data">
  
  {% csrf_token %}


    <div class="row">
      <div>
        <div class="card-body" style="width: 50%">
          <h1>Add author</h1>

          {{form_author.id}}

          <div class="mb-3">
            <label class="form-label">Fullname</label>
            {{form_author.fullname}}
            <span>{{ form_author.errors.fullname }}</span>
          </div>

          <div class="mb-3">
            <form>
              <div class="form-group">
                <label for="inputDate" class="form-label">Was born</label>
                {{ form_author.born_date }}
                <span>{{ form_author.errors.born_date }}</span>
                
              </div>
            </form>
          </div>

          <div class="mb-3">
            <label class="form-label">Born in</label>
            {{form_author.born_location}}
            <span>{{ form_author.errors.born_location }}</span>
          </div>

          <div class="mb-3">
              <label class="form-label">Description</label>
              {{form_author.description}}
              <span>{{ form_author.errors.description }}</span>
          </div>

        <button type="submit" class="btn btn-secondary">Save</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
      </div>      
    </div>

</form> 

{% endblock %}

quotes/app_quotes/templates/app_quotes/add_quote.html
{% extends "app_quotes/base.html" %}

{% block content %}

<form action="{% url 'app_quotes:add_quote' %}" method="POST" enctype="multipart/form-data">

    {% csrf_token %}


        <div class="row">
          <div>
            <div class="card-body" style="width: 50%;">

              <h1>Add quote</h1>
              {{form_quote.id}}

              <div class="mb-3">
                <label class="form-label">Quote</label>
                {{form_quote.quote}}
                <span>{{ form_quote.errors.quote }}</span>
              </div>

              <div class="mb-3">
                <label class="form-label">Author</label>
                {{form_quote.author}}
                <span>{{ form_quote.errors.author }}</span>
              </div>

              <div class="mb-3">
                <label class="form-label">Tags</label>
                {{form_quote.tags}}
                <span>{{ form_quote.errors.tags }}</span>
              </div>

            <button type="submit" class="btn btn-secondary">Save</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
          </div>
        </div>
      </div>

</form>  

{% endblock %}

quotes/app_quotes/templates/app_quotes/authors.html
{% extends "app_quotes/base.html" %}

{% block content %}


    <h1>About authors</h1>
    <div class="row">

        {% for author in authors %}

            <div class="card">
                <h5 class="card-header">{{author.fullname}}</h5>
                <div class="card-body">
                    <p class="card-text"><strong>Born: </strong>{{author.born_date}} in {{author.born_location}}</p>
                    <p class="card-text">{{author.description}}</p>
                </div>

            </div>
        <p>&nbsp;</p>
        {% endfor %}

    </div>

 
{% endblock %}

quotes/app_quotes/templates/app_quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Quotes</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:main' %}">Quotes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:authors' %}">Authors</a>
                    </li>


                    {% if user.is_authenticated %}


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:add_author' %}">Add author</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:add_quote' %}">Add quote</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">LogOut</a>
                    </li>


                    {% else %}


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">SignIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">SignUp</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

quotes/app_quotes/templates/app_quotes/index.html
{% extends "app_quotes/base.html" %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="#" alt="" width="72" height="57">
    <h1 class="display-5 fw-bold">Centered hero</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most
            popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system,
            extensive prebuilt components, and powerful JavaScript plugins.</p>
<!--        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">-->
<!--            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>-->
<!--            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>-->
<!--        </div>-->
    </div>
</div>

{% endblock %}

quotes/app_quotes/templates/app_quotes/quotes.html
{% extends "app_quotes/base.html" %}

{% block content %}


  <h1>Quotes</h1>

  <div class="row">

        {% for quote in quotes %}

            <div class="card">
                <h5 class="card-header">{{quote.quote}}</h5>
                <div class="card-body">
                    <p class="card-text"><strong>Author: </strong>{{quote.author}}
                        <a href="{% url 'app_quotes:authors' %}?id={{ quote.author_id }}">(about)</a>
                    </p>
                    <p class="card-text">Tags: {% for tag in quote.tags %}
                        <a href="{% url 'app_quotes:tags' %}?tag={{ tag }}"</p>
                        {{ tag }}
                        </a>
                        {% endfor %}
                </div>

            </div>
        <p>&nbsp;</p>

      {% endfor %}
  </div>


{% endblock %}

quotes/app_quotes/templates/app_quotes/tags.html
{% extends "app_quotes/base.html" %}

{% block content %}


    <h1>Tag: {{tag}}</h1>
    <div class="row">

        {% for quote in quotes %}

            <div class="card">
                <h5 class="card-header">{{quote.quote}}</h5>
                <div class="card-body">
                    <p class="card-text"><strong>Author: </strong>{{quote.author}}
                        <a href="{% url 'app_quotes:authors' %}?id={{ quote.author_id }}">(about)</a>
                    </p>
                    <p class="card-text">Tags: {% for tag in quote.tags %}
                        <a href="{% url 'app_quotes:tags' %}?tag={{ tag }}"</p>
                        {{ tag }}
                        </a>
                        {% endfor %}
                </div>

            </div>
        <p>&nbsp;</p>
        {% endfor %}

    </div>

{% endblock %}